# -*- mode: ruby -*- 
# vi: set ft=ruby : 
 
 
Vagrant.configure("2") do |config| 
 
    # We set up one box, without any networking options 
      # This will establish one interface on the guest machine, 
      # using NAT networking and a forwarding rule for incoming SSH traffic 
      config.vm.define "worker2" do |vm1| 
      config.ssh.private_key_path = "/home/winpaing/Desktop/Kubernetes_lab/setup/worker2/.ssh/worker2_rsa" 
      config.ssh.forward_agent = true 
      config.ssh.username = "vagrant" 
      config.ssh.password = "vagrant" 
        vm1.vm.hostname = "worker2" 
        vm1.vm.box = "bento/ubuntu-22.04"
  vm1.vm.network "private_network", ip: "192.168.56.22", :name => 'vboxnet0'  
        vm1.vm.synced_folder ".", "/home/vagrant/" 
        vm1.vm.provider "virtualbox" do |vb| 
          vb.name = "worker2" 
        end 
      end 
    end
